website/__init__.py
from typing import Optional

from flask import Flask, session, url_for
from flask_socketio import SocketIO

from .room import Room, Player

rooms = {}

def find_game(pin: str) -> Optional[Room]:
    return rooms.get(pin)

def del_room(pin: str) -> None:
    if pin in rooms.keys():
        del rooms[pin]

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret!'
    socketio = SocketIO(app)


    from .views import views
    from .event_handlers.room_events import register_room_events
    from .event_handlers.bot_events import register_bot_events
    # from .event_handlers.game_events import register_game_events

    register_room_events(app, socketio)
    register_bot_events(socketio)
    # register_game_events(socketio)

    app.register_blueprint(views, url_prefix='/')

    return app, socketio

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session, json, flash
from flask_socketio import leave_room

from . import find_game, cfg, rooms
from .room import check_unique_colors, pick_random_colors, color_exists

views = Blueprint('views', __name__)


@views.route('/')
@views.route('/home')
def home_page():

    return render_template("home.html")

@views.route('/room-owner', methods=['GET', 'POST'])
def room_owner():
    if request.method == 'POST':
        from .room import Room
        from . import rooms
        import random
        while True:
            pin = str(random.randint(1000, 9999))
            curr_game = find_game(pin)
            if curr_game is None:
                break

        game_type = request.form.get('game')
        curr_game = Room(game_type)
        player = curr_game.add_player(is_owner=True)
        rooms[pin] = curr_game

        session['room'] = pin
        session['player'] = vars(player)

        players = [vars(p) for p in curr_game.players]
        colors = [vars(p)['color'] for p in curr_game.players]
        while player.color in colors:
            player.color = pick_random_colors(1)
        player_dict = {pla['id']: pla['name'] for pla in players}

        return render_template("room-owner.html", players=player_dict, bots=cfg.avail_bots, game_pin=pin, token=player.token, color=player.color)

    # if tried to enter /room-owner directly - redirect to choose
    return redirect(url_for('.choose'))

@views.route('/room-player', methods=['GET', 'POST'])
def room_player():
    if request.method == 'POST':
        from . import rooms

        pin = request.form.get('pin')
        curr_game = find_game(pin)

        if curr_game is None:
            flash('Room with given id does not exist', 'alert-danger')  # second parameter must be existing class in BootStrap !
            return redirect(url_for('.choose'))

        # r = session.get('room')
        # if r == pin:
        #     return render_template("room-player.html", players=[p.to_json() for p in curr_game.players], game_pin=pin)

        if curr_game.started:
            flash('Game already started', 'alert-danger')  # second parameter must be existing class in BootStrap !
            return redirect(url_for('.choose'))

        player = curr_game.add_player()
        if not player:
            flash('Room is full', 'alert-info')
            return redirect(url_for('.choose'))

        rooms[pin] = curr_game

        session['room'] = pin
        session['player'] = vars(player)

        players = [vars(p) for p in curr_game.players]

        colors =  [vars(p)['color'] for p in curr_game.players]
        while player.color in colors:
            player.color = pick_random_colors(1)

        player_dict = {pla['id']: pla['name'] for pla in players}

        return render_template("room-player.html", players=player_dict, actual_player_id=player.id, game_pin=pin, token=player.token, color=player.color)

    # if tried to enter /room-player directly - redirect to choose
    return redirect(url_for('.choose'))

@views.route('/choose')
def choose():
    msg = request.args.get('msg')
    if msg: flash(msg, 'alert-info')
    # cannot clear session (flashing not work), but can clear room associated wth session to keep no duplicating player during refresh
    # Solutions
    # 1. left it like it is, clearing only room associated with session and keep flasking working
    # 2. clear whole session and flashing not work, so we will need to write our own popups with info for players
    session['room'] = None
    return render_template("choose.html")

@views.route('/game')
def game():
    room = session.get('room')
    player = session.get("player")
    curr_game = find_game(room)
    if not room or not player:
        flash('You aren\'t assigned to this room', 'alert-danger')
        return redirect(url_for('.choose'))
    if not curr_game:
        flash('Room with given id does not exist', 'alert-danger')
        return redirect(url_for('.choose'))
    if not curr_game.started:
        flash('Game has not started yet', 'alert-danger')
        return redirect(url_for('.choose'))

    print(player)

    safe_players = [player.to_safe_json() for player in curr_game.players]
    print(safe_players)

    return render_template('game.html', players=safe_players, actual_player_id=player["id"], color=player["color"])

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--Link to tab icon-->
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/logo_cat.png') }}">
    <!--Links to google fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <!--Links to Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous"/>
    <!--BS icons--><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <!--Links to local styles-->
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/base.css') }}" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
      <script
      src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
      integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
      crossorigin="anonymous"
    ></script>
    {% block links %} {% endblock %}

    <title>{% block title %} Base {% endblock %}</title>
  </head>
  <body style="background-image: url({{ url_for('static', filename='images/background.png') }});">
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark navbar_custom">
      <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <span class="website_text">
                <img src="{{ url_for('static', filename='images/logo_cat.png') }}" alt="" class="d-inline-block align-text-top website_logo">
                <span style="color: var(--accent-nope);">AI</span>ighieri
            </span>
          </a>
            {% if request.url_rule.rule == '/' or request.url_rule.rule == '/home' %}
                <div class="collapse navbar-collapse justify-content-end">
                  <div class="navbar-nav" style="text-align: right;">
                   <!--TODO: log in-->
                    <a class="nav-link" href="#"></a>
                  </div>
                </div>
            {% endif %}
      </div>
    </nav>

    <div class="container" style="max-width: 80%;">
        <!--This alert is generated by flash function with parameters: [msg, bs-class]-->
        <!--example flask('msg to show', 'alert-danger') second parameter must be existing class for alerts in BootStrap-->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert {{ category }} alert-dismissible fade show" role="alert" style="width: 100%; position: absolute; left: 0px;">
                        <strong>{{ message }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <!--All alerts will be automatically closed after 5 sec-->
        <script type="text/javascript">
            setTimeout(function () { $('.alert').alert('close'); }, 5000);
        </script>

        {% block content %}
        {% endblock %}
    </div>


    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

  </body>
</html>

website/templates/choose-game.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}
{% block content %}
    <script>
      $(document).ready(function() {
        $('#join-pacman').click(function() {
          $('#join-pacman').hide();
          $('#text-field-pacman').show();
        });
      });
    </script>
    <script>
      $(document).ready(function() {
        $('#join-pong').click(function() {
          $('#join-pong').hide();
          $('#text-field-pong').show();
        });
      });
    </script>
    <div class="choose-game-rectangle" style="left: 15%;top: 20%;">
        <div class="wrapper">
            <img class ="choose-game-image" src="{{ url_for('static', filename='images/pacman.png') }}" alt="pacman">
        </div>
        <div class="choose-game-button-text-align">
            <button class="choose-game-button" onclick="window.location.href='/new-game'" style="left:3%">Stworz pokoj</button>
            <button id = "join-pacman" class="choose-game-button" style="left:53%">Dolacz</button>
            <input class="choose-game-text-field"  type = "text" id="text-field-pacman" style="display: none;left:53%; ">

        </div>
   </div>
   <div class="choose-game-rectangle" style="left: 55%;top: 20%;">
       <img class ="choose-game-image" src="{{ url_for('static', filename='images/pong.png') }}"  alt="pong">
       <div class="choose-game-button-text-align">
            <button class="choose-game-button" onclick="window.location.href='/new-game'" style="left:3%">Stworz pokoj</button>
            <button  id ="join-pong" class="choose-game-button" style="left:53%">Dolacz</button>
            <input class="choose-game-text-field"  type = "text" id="text-field-pong" style="display: none;left:53%; ">
       </div>
   </div>

{% endblock %}

website/templates/choose.html
{% extends "base.html" %}
{% block links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/choose.css') }}" />
{% endblock %}
{% block title %} Home {% endblock %}
{% block content %}
    <div class="choose-container">
        <div class="choose-rectangle" style="top: 20%; height: 30%">
            <div class="choose-button-text-align">
                <h3 class="choose-text" style="top: 20%;left: 10%;">Join existing game</h3>
                <form action="/room-player" method="post">
                    <button type ="submit" class="choose-button"  style="left:70%">Join</button>
                    <input class="choose-text-field" name="pin" type = "text" id="text-field" style="left:10%; ">
                </form>
        </div>
   </div>
<!--TODO: this style must be changed, for automate generating divs, positioning by top, left etc. with percent has no sense-->
<!--TODO: we also should try to avoid setting style "inline"-->
<!--But for now it can be like this-->
   <div class="choose-rectangle" style="top: 65%;height: 100%">
       <div class="choose-button-text-align">
            <h3 class="choose-text" style="top: 10%;left: 10%;">Create new room</h3>
       </div>
       <!--One form instead of n forms, we will recognize what game is by value parameter in button-->
       <!--IMPORTANT request.form.get() method in views.py will search by "name" parameter and take value from "value" parameter in each button-->
       <form method="POST" action="/room-owner">
          <button type="submit" class="submit-button"  name="game" value="pac-man">
              <img style="top: 20%;left: 7.5%;" class ="choose-image" src="{{ url_for('static', filename='images/pacman.png') }}"  alt="pacman">
          </button>
          <button type="submit" class="submit-button"  name="game" value="pong">
              <img style="top: 20%;left: 52.5%;" class ="choose-image" src="{{ url_for('static', filename='images/snake.png') }}"  alt="snake">
          </button>
          <button type="submit" class="submit-button"  name="game" value="pac-man">
              <img  style="top: 60%;left: 7.5%;" class ="choose-image" src="{{ url_for('static', filename='images/coming_soon.png') }}"  alt="pacman">
          </button>
          <button type="submit" class="submit-button" name="game" value="pong" >
              <img  style="top: 60%;left: 52.5%;" class ="choose-image" src="{{ url_for('static', filename='images/coming_soon.png') }}"  alt="pong">
          </button>
       </form>
   </div>
    </div>
{% endblock %}

website/templates/game.html
{% extends "base.html" %}
{% block links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/home.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/game.css') }}" />

    <script src="{{ url_for('static', filename='scripts/timer.js') }}"></script>
    <script type="text/javascript"  src ="{{ url_for('static', filename='scripts/game-events.js') }}"></script>
{% endblock %}
{% block title %} Game {% endblock %}
{% block content %}

<!-- START popup / modal -->
<div class="modal fade" id="endgame_popup" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content ls-modal-style">
            <div class="modal-header">
                <div class="modal-title ls-modal-title ls-player-name"><h4>Player scores</h4></div>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer ls-modal-footer">
                <button type="button" class="shadow-none btn btn-lg btn-block btn-success rounded-pill ls-close-button" onclick="leave_game('{{ url_for('views.choose')}}')">Exit</button>
            </div>
        </div>
    </div>
</div>
<!-- END popup / modal -->

<div class="container_game">
    <div class="row">
            <canvas id ="screen">
                <!--TODO: Make this universal to choosed game-->
            </canvas>
    </div>
    <div class="row">
        <div class="col-sm-6 col-xs-12">
            <div class="grid_div center_div" style="margin-top: 25px;">
                <div id="player-list">

                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xs-12">
            <div class="grid_div center_div" style="margin-top: 25px;">
                <div class="timer">
                    <!--TODO: finish session, connection etc, when we create this feature-->
                    <!--TODO: reset timer when we get back by browser arrow-->
                    <span id="time">15:00</span>    <!--after 30s timer finish counting and redirect to the choose page (by JS)-->
                </div>

                <button type="button" class="shadow-none btn btn-lg btn-block btn-success rounded-pill ls-close-button" onclick="leave_game('{{ url_for('views.choose')}}')">End game</button>
            </div>
        </div>
    </div>
</div>

<script>
    var actual_player_id = {{ actual_player_id }}
    const backgroundColor = '{{ color[0] }}';
    console.log(backgroundColor)
    console.log(actual_player_id)
</script>

<script>
    {% for player in players %}
        addPlayer(JSON.parse('{{ player | tojson }}'));
    {% endfor %}
</script>


<script type="text/javascript"  src ="{{ url_for('static', filename='scripts/game-rendering.js') }}" defer></script>

{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/home.css') }}" />
{% endblock %}
{% block title %} Home {% endblock %}
{% block content %}

    <div class="container_home">
        <div class="row">
            <div class="col-sm-6 col-xs-12 col_div">
                <div class="grid_div center_div fill">
                    <img src="{{ url_for('static', filename='images/about.png') }}" style="max-height: 300px; width: auto;" alt="">
                </div>
            </div>
            <div class="col-sm-6 col-xs-12 col_div">
                <div class="grid_div center_div">
                    <h1>What is Alighieri?</h1>
                    <p>Welcome to Alighieri - a platform for testing artificial intelligence algorithms on multiplayer games.
                        With this platform, which allows you to run algorithms locally on your computer and then send the necessary commands using our API, you can test your algorithms and compete with your friends.
                        Join our community today and start developing your projects!</p>
                </div>
            </div>
        </div>
        <!--TODO create grid with games based on somekind jsonfile (easy way to add new things)-->
        <div class="row">
            <div class="col col_div">
                <div class="grid_div center_div grid_long_div">
                    <h3 style="text-align: center;">Available games</h3>
                    <div class="row">
                        <div class="col-sm-4 col-xs-12 col_div">
                            <div class="grid_div center_div fill game_image">
                                <img src="{{ url_for('static', filename='images/pacman.png') }}" alt="">
                            </div>
                        </div>
                        <div class="col-sm-4 col-xs-12 col_div">
                            <div class="grid_div center_div fill game_image">
                                <img src="{{ url_for('static', filename='images/snake.png') }}" alt="">
                            </div>
                        </div>
                        <div class="col-sm-4 col-xs-12 col_div">
                            <div class="grid_div center_div fill game_image">
                                <img src="{{ url_for('static', filename='images/coming_soon.png') }}" alt="">
                            </div>
                        </div>
                    </div>
                    
                    <button type=" button" class="shadow-none btn btn-lg btn-block btn-success rounded-pill enter-button" onclick="window.location.href='/choose'">Go to games</button>
                </div>
            </div>
         </div>
        <div class="row">
            <div class="col-sm-6 col-xs-12 col_div">
                <div class="grid_div center_div">
                    <h1>About us</h1>
                <p>We are a young dynamic student team with interests focused broadly on artificial intelligence.
                    We are aware of the fact that when writing algorithms or bots based on AI, there will often appear all sorts of problems that are hard to see at first glance and which cause discouragement in this exciting topic.
                    For this reason, we have decided together to build a platform for testing artificial intelligence algorithms written by users.</p>

                </div>
            </div>
            <div class="col-sm-6 col-xs-12 col_div">
                <div class="grid_div center_div fill">
                    <img src="{{ url_for('static', filename='images/us.png') }}" style="max-height: 300px; width: auto;" alt="">
                </div>
            </div>
        </div>
    </div>

{% endblock %}

website/templates/room-owner.html
{% extends "base.html" %}
{% block links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/home.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/game.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/room.css') }}" />

    <script type="text/javascript"  src ="{{ url_for('static', filename='scripts/common-events.js') }}"></script>
    <script type="text/javascript"  src ="{{ url_for('static', filename='scripts/room-owner-events.js') }}"></script>
{% endblock %}
{% block title %} Room {% endblock %}
{% block content %}
<div class="container_game">
    <div class="room-rectangle center_div">
        <div class="room-pin-container">
            <span class="room-subtext">Room code</span>
            <p class="room-pin" style="margin-bottom: 0">{{game_pin}}</p>
        </div>
        <div class="room-pin-container">
            <span class="room-subtext">Token</span>
            <p class="room-token">{{ token }}</p>
        </div>

        <div id="player-list">

        </div>
        <div style="text-align: center;">
            <button class="ls-button ls-cancel-game-button" onclick="leave('{{ url_for('views.choose') }}')">Cancel</button>
            <button class="ls-button ls-start-game-button" onclick="startGame()">Start game</button>
            <div class="dropdown ls-dropdown-div">
                <button class="shadow-none btn btn-lg btn-secondary dropdown-toggle btn-success rounded-pill ls-dropdown-btn ls-extended-button" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Add bot
                </button>
                <!--TODO: style dropdown list, add pointer on hover-->
                <div class="dropdown-menu ls-dropdown-menu" aria-labelledby="dropdownMenuButton">
                    {% for b_key, b_val in bots.items() %}
                        <!--For now only b_key is used (b_key == bot name), we have to consider what data bots need to work-->
                        <span class="dropdown-item" onclick="addBot('{{ b_key }}', '{{ b_val }}')">{{ b_key }}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="form-check">
                <div class="row px-5">
                    <div class="col-2 col-md-2 pl-5 pr-0">
                        <input class="form-check-input ls-random-map-checkbox" type="checkbox" value="" id="generateRandomMap">
                    </div>
                    <div class="col-10 col-md-10 pr-5 pl-0">
                        <label class="form-check-label ls-random-map-label" for="generateRandomMap">
                            Generate random map
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    const backgroundColor = '{{ color[0] }}';
</script>
{% for player_id, player_name in players.items() %}
    <script>
        addPlayer({ id: {{ player_id }}, name: '{{ player_name }}' });
    </script>

{% endfor %}

{% endblock %}

website/templates/room-player.html
{% extends "base.html" %}
{% block links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/home.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/game.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/room.css') }}" />

    <script type="text/javascript"  src ="{{ url_for('static', filename='scripts/common-events.js') }}"></script>
    <script type="text/javascript"  src ="{{ url_for('static', filename='scripts/room-player-events.js') }}"></script>
{% endblock %}
{% block title %} Home {% endblock %}
{% block content %}
<div class="container_game">
    <div class="room-rectangle center_div">
        <div class="room-pin-container">
            <span class="room-subtext">Room code</span>
            <p class="room-pin" style="margin-bottom: 0">{{game_pin}}</p>
        </div>
         <div class="room-pin-container">
             <span class="room-subtext">Token</span>
             <p class="room-token">{{ token }}</p>
        </div>
            <div id="player-list">

            </div>
        <div style="text-align: center;">
            <button class="ls-button ls-cancel-game-button" onclick="leave('{{ url_for('views.choose') }}')">Exit</button>
        </div>
    </div>
</div>

<script>
    var actual_player_id = {{ actual_player_id }}
    const backgroundColor = '{{ color[0] }}';
</script>

{% for player_id, player_name in players.items() %}
    <script>
        addPlayer({ id: {{ player_id }}, name: '{{ player_name }}' });
    </script>
{% endfor %}

{% endblock %}